### Install and Import Dependencies

In [2]:
!pip install tensorflow==2.4.1 opencv-python matplotlib

  Using cached tensorflow-2.4.1-cp37-cp37m-win_amd64.whl (370.7 MB)
  Using cached opencv_python-4.7.0.72-cp37-abi3-win_amd64.whl (38.2 MB)
     ---------------------------------------- 7.2/7.2 MB 4.4 MB/s eta 0:00:00
  Using cached Keras_Preprocessing-1.1.2-py2.py3-none-any.whl (42 kB)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
  Using cached typing_extensions-3.7.4.3-py3-none-any.whl (22 kB)
     ---------------------------------------- 2.5/2.5 MB 4.3 MB/s eta 0:00:00
  Using cached tensorflow_estimator-2.4.0-py2.py3-none-any.whl (462 kB)
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
  Using cached termcolor-1.1.0-py3-none-any.whl
  Using cached grpcio-1.32.0-cp37-cp37m-win_amd64.whl (2.5 MB)
  Using cached gast-0.3.3-py2.py3-none-any.whl (9.7 kB)
  Using cached tensorboard-2.11.2-py3-none-any.whl (6.0 MB)
  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
  Using cached absl_py-0.15.0-py3-non

In [1]:
import tensorflow as tf
import numpy as np
from matplotlib import pyplot as plt
import cv2

### Load Model

In [2]:
interpreter=tf.lite.Interpreter(model_path='lite-model_movenet_singlepose_lightning_3.tflite')
interpreter.allocate_tensors()

### Make Detections

In [17]:
cap=cv2.VideoCapture(0)
while cap.isOpened():
    ret, frame= cap.read()
    
    #Reshape image for the model
    img=frame.copy()
    #excapsulating in another array with numpy
    img=tf.image.resize_with_pad(np.expand_dims(img,axis=0),192,192)
    input_image=tf.cast(img,dtype=tf.float32)
    
    #Setup input and output
    input_details=interpreter.get_input_details()
    output_details=interpreter.get_output_details()
    
    #Make Predictions
    interpreter.set_tensor(input_details[0]['index'],np.array(input_image))
    interpreter.invoke()
    keypoints_with_scores=interpreter.get_tensor(output_details[0]['index'])
    print(keypoints_with_scores)
    
    #rendering 
    draw_connections(frame, keypoints_with_scores, EDGES, 0.4)
    draw_keypoints(frame, keypoints_with_scores, 0.4)
    
    cv2.imshow('Movenet Lightning', frame)
    #q to quit
    if cv2.waitKey(10) & 0xFF==ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

[[[[0.21199065 0.49960434 0.65868783]
   [0.17938314 0.53553665 0.7705645 ]
   [0.17826548 0.46148694 0.7820861 ]
   [0.22562318 0.5859563  0.5733847 ]
   [0.22134149 0.40385982 0.74203086]
   [0.37581533 0.6268343  0.8822855 ]
   [0.37746406 0.32829085 0.9281884 ]
   [0.56164086 0.80109423 0.71535856]
   [0.6577909  0.28311795 0.662272  ]
   [0.64085835 0.9846965  0.29180852]
   [0.83517146 0.48116407 0.3694194 ]
   [0.8000742  0.6142497  0.6519835 ]
   [0.81814265 0.38992274 0.7178398 ]
   [0.7729644  0.82193446 0.29927105]
   [0.86627984 0.4971525  0.11158326]
   [0.8540337  0.55526495 0.09328932]
   [0.85923505 0.5939305  0.1185621 ]]]]
[[[[0.21574675 0.49441025 0.5445477 ]
   [0.18273282 0.5327642  0.7484402 ]
   [0.17986786 0.45974645 0.76322293]
   [0.22772717 0.585413   0.56419075]
   [0.21828906 0.40683895 0.79442966]
   [0.3784564  0.6266367  0.7526252 ]
   [0.37914926 0.3275988  0.9431852 ]
   [0.56358194 0.8028976  0.71037954]
   [0.6523534  0.2829098  0.80194354]
   [0.639

[[[[0.21388173 0.6344237  0.68458974]
   [0.1792753  0.62175965 0.50858253]
   [0.17888367 0.5949891  0.65970093]
   [0.20317939 0.5175993  0.5527787 ]
   [0.20967947 0.45076248 0.7065179 ]
   [0.38258132 0.63284826 0.8851752 ]
   [0.37520835 0.32932502 0.7855668 ]
   [0.5624963  0.8090029  0.6837218 ]
   [0.65366495 0.2842358  0.5753065 ]
   [0.6446101  0.98724496 0.3153062 ]
   [0.8302579  0.50538254 0.2406494 ]
   [0.8200369  0.6143248  0.59764427]
   [0.8379244  0.37999654 0.5190285 ]
   [0.8385436  0.9397193  0.07971099]
   [0.8561528  0.49505728 0.06318602]
   [0.84264076 0.57283163 0.04446289]
   [0.86043274 0.64895606 0.06692868]]]]
[[[[0.21460013 0.6328335  0.70211154]
   [0.18024987 0.61521184 0.69336957]
   [0.1802744  0.59427226 0.60133314]
   [0.20292608 0.5020658  0.6270297 ]
   [0.20774311 0.45215556 0.75187266]
   [0.38195753 0.6313621  0.88256335]
   [0.37633276 0.33142757 0.8241527 ]
   [0.56294817 0.8096186  0.71061283]
   [0.6514693  0.28288302 0.55367416]
   [0.643

[[[[0.22234812 0.4863649  0.85689175]
   [0.20402241 0.51755834 0.716692  ]
   [0.20320293 0.45915386 0.7409681 ]
   [0.25200504 0.56914246 0.5924782 ]
   [0.25384304 0.42866033 0.77748346]
   [0.38245118 0.63062537 0.9384989 ]
   [0.38124868 0.36295372 0.71452016]
   [0.5579965  0.7470559  0.6704278 ]
   [0.5551001  0.23367354 0.48036897]
   [0.58939517 0.90816754 0.35094428]
   [0.712693   0.2446162  0.43067873]
   [0.7460157  0.5919479  0.76395226]
   [0.7430552  0.4045144  0.8394201 ]
   [0.768131   0.8038632  0.3547485 ]
   [0.5463847  0.21997182 0.6416436 ]
   [0.8056598  0.56954956 0.18695667]
   [0.7937169  0.42208672 0.08663508]]]]
[[[[0.23526108 0.47872126 0.6004957 ]
   [0.21573472 0.5071739  0.83114904]
   [0.21473466 0.45083547 0.8386823 ]
   [0.259054   0.552681   0.72289073]
   [0.26034302 0.4172486  0.72327447]
   [0.3836014  0.6080574  0.9217883 ]
   [0.38791117 0.34511483 0.82887447]
   [0.5573186  0.7099887  0.59307206]
   [0.5448451  0.22632407 0.7712687 ]
   [0.575

[[[[0.30162436 0.42923045 0.7341274 ]
   [0.2885534  0.45304748 0.6661042 ]
   [0.2866474  0.41350982 0.6316646 ]
   [0.31569386 0.48861265 0.7371803 ]
   [0.3096671  0.3891248  0.6747894 ]
   [0.40089333 0.5374777  0.8414553 ]
   [0.39671978 0.33173066 0.7407317 ]
   [0.5081549  0.6067296  0.7343194 ]
   [0.5078826  0.26707286 0.6122396 ]
   [0.61171484 0.56178874 0.55450064]
   [0.60466    0.256733   0.391021  ]
   [0.67508215 0.48300505 0.79261637]
   [0.6697891  0.3609897  0.77207625]
   [0.8388676  0.49589127 0.3247404 ]
   [0.8438906  0.30086917 0.4985587 ]
   [0.86310923 0.48661417 0.02080283]
   [0.86931413 0.31819153 0.02577186]]]]
[[[[0.30162436 0.42923045 0.7341274 ]
   [0.2885534  0.45304748 0.6661042 ]
   [0.2866474  0.41350982 0.6316646 ]
   [0.31569386 0.48861265 0.7371803 ]
   [0.3096671  0.3891248  0.6747894 ]
   [0.40089333 0.5374777  0.8414553 ]
   [0.39671978 0.33173066 0.7407317 ]
   [0.5081549  0.6067296  0.7343194 ]
   [0.5078826  0.26707286 0.6122396 ]
   [0.611

[[[[0.3583194  0.3636541  0.6925117 ]
   [0.34355932 0.38198408 0.73005617]
   [0.34417915 0.3468977  0.78463733]
   [0.3566769  0.41592622 0.4962058 ]
   [0.35910138 0.32440534 0.7012656 ]
   [0.4126396  0.45764893 0.63401914]
   [0.4166871  0.29612714 0.6503065 ]
   [0.4791227  0.52397156 0.40467817]
   [0.46896967 0.2501717  0.48723596]
   [0.46730703 0.48740157 0.30886966]
   [0.467986   0.2627004  0.27124757]
   [0.6202828  0.435556   0.6334123 ]
   [0.6174209  0.338098   0.6829362 ]
   [0.77164793 0.44445488 0.5577414 ]
   [0.70694053 0.25810665 0.58158463]
   [0.7679806  0.4332227  0.20062423]
   [0.7963647  0.29300857 0.27874506]]]]
[[[[0.35543257 0.36626476 0.62251943]
   [0.33980975 0.3850367  0.70272565]
   [0.33786124 0.3481898  0.71647674]
   [0.35598716 0.4165144  0.54891855]
   [0.3551709  0.32109976 0.68157315]
   [0.41535032 0.45610723 0.6367574 ]
   [0.4146577  0.28473356 0.60002995]
   [0.4819237  0.5054352  0.3928023 ]
   [0.47492135 0.24459854 0.5191781 ]
   [0.485

[[[[0.12866147 0.45492435 0.4033816 ]
   [0.11543118 0.46690497 0.32923642]
   [0.11180028 0.4407133  0.24330014]
   [0.13383503 0.49052557 0.5760735 ]
   [0.11753118 0.4059978  0.49228692]
   [0.22084706 0.5132453  0.7650721 ]
   [0.19582498 0.34411466 0.83919966]
   [0.35203314 0.51600915 0.63264656]
   [0.31686002 0.28737414 0.62462574]
   [0.47038907 0.49543402 0.6268103 ]
   [0.4411419  0.28878257 0.74792576]
   [0.47594976 0.44763815 0.7960386 ]
   [0.4676803  0.34489554 0.8528456 ]
   [0.65588635 0.46150124 0.6920998 ]
   [0.6326138  0.31033462 0.7183772 ]
   [0.76532024 0.4554095  0.4057746 ]
   [0.7814979  0.29910427 0.6570382 ]]]]
[[[[0.11285464 0.47659886 0.15161589]
   [0.09295611 0.48321232 0.15057385]
   [0.09136947 0.463749   0.13082248]
   [0.11449262 0.5012333  0.40210044]
   [0.10557636 0.43788704 0.28839985]
   [0.20948249 0.52854013 0.73365074]
   [0.19159737 0.36378866 0.7520858 ]
   [0.34066233 0.549347   0.5933682 ]
   [0.31039515 0.31034684 0.6467613 ]
   [0.469

[[[[0.11650389 0.39144754 0.14531487]
   [0.09773754 0.40717575 0.08722338]
   [0.09287272 0.3834266  0.11894166]
   [0.10815912 0.42782122 0.30417228]
   [0.10130145 0.35820216 0.15120158]
   [0.19285345 0.47472775 0.6359518 ]
   [0.19659662 0.3037195  0.8707413 ]
   [0.33989477 0.5174018  0.65774447]
   [0.3581956  0.2861555  0.8127456 ]
   [0.4474333  0.561321   0.54761565]
   [0.47568756 0.30422044 0.5785248 ]
   [0.44178018 0.4891175  0.6580227 ]
   [0.45787227 0.38003677 0.7931161 ]
   [0.62567997 0.49327156 0.36382133]
   [0.62600774 0.38105413 0.69534373]
   [0.708794   0.48716623 0.55779517]
   [0.7512491  0.3676548  0.43855166]]]]
[[[[0.12380247 0.3943075  0.21499297]
   [0.10501932 0.40800864 0.1186218 ]
   [0.10291787 0.387147   0.12090611]
   [0.11202095 0.42875764 0.336807  ]
   [0.10659727 0.36241803 0.20422667]
   [0.19295755 0.47898054 0.65626895]
   [0.19554827 0.30821937 0.8118342 ]
   [0.33248195 0.5113439  0.5269677 ]
   [0.35104698 0.28809607 0.8185564 ]
   [0.429

[[[[0.10000511 0.5300796  0.08143175]
   [0.07989686 0.5284009  0.09943348]
   [0.08113354 0.5364656  0.07932326]
   [0.09668188 0.5456223  0.12285089]
   [0.09702793 0.55052966 0.16945052]
   [0.18805932 0.56532645 0.34718952]
   [0.18716946 0.566136   0.29996416]
   [0.3512993  0.65098476 0.38656855]
   [0.34169048 0.5224263  0.16029721]
   [0.4827759  0.64547276 0.33975953]
   [0.4506646  0.49639058 0.12187484]
   [0.465875   0.54071164 0.6257779 ]
   [0.46100315 0.5215125  0.54588395]
   [0.5058629  0.3678733  0.42417985]
   [0.6337314  0.5128695  0.10910192]
   [0.7220937  0.43092987 0.4986417 ]
   [0.7193171  0.43584737 0.26440668]]]]
[[[[0.12575124 0.53402805 0.15864912]
   [0.10217361 0.53463525 0.11430377]
   [0.10186285 0.53787595 0.08292076]
   [0.10903614 0.54118127 0.18419316]
   [0.10874768 0.54424965 0.18217245]
   [0.18879019 0.5560545  0.3428052 ]
   [0.18399346 0.5435858  0.24936217]
   [0.3419332  0.6265551  0.20117712]
   [0.3443595  0.5827944  0.15147933]
   [0.475

[[[[0.07417304 0.51700544 0.03505948]
   [0.0338364  0.5274995  0.04798838]
   [0.03565696 0.51117647 0.03848091]
   [0.06483513 0.5635536  0.0843243 ]
   [0.0625655  0.504533   0.07349348]
   [0.1740408  0.6259841  0.70157534]
   [0.17395082 0.4440505  0.77425635]
   [0.33834076 0.65435123 0.6961514 ]
   [0.31779078 0.4131292  0.64322615]
   [0.4696289  0.6000748  0.6308146 ]
   [0.4440138  0.39660022 0.49533674]
   [0.45512915 0.5541421  0.6559266 ]
   [0.44748682 0.452818   0.88247955]
   [0.6316473  0.5610367  0.6436004 ]
   [0.5841161  0.3577853  0.6189881 ]
   [0.74590874 0.5645381  0.42715937]
   [0.75070876 0.36110362 0.7816198 ]]]]
[[[[0.09357517 0.51466113 0.05559149]
   [0.05463379 0.52035797 0.05083257]
   [0.04736429 0.50401247 0.0597218 ]
   [0.08058749 0.5592116  0.0767099 ]
   [0.07652675 0.49662447 0.0992603 ]
   [0.1768592  0.61682117 0.7115536 ]
   [0.18240502 0.43199897 0.6070335 ]
   [0.33512267 0.6554905  0.46274966]
   [0.32789573 0.39539707 0.66149426]
   [0.460

[[[[0.01597054 0.2759514  0.04083863]
   [0.00562593 0.28657606 0.02525482]
   [0.00811316 0.26413304 0.0216468 ]
   [0.02016556 0.33125794 0.07537746]
   [0.02682813 0.28072453 0.06236115]
   [0.14417279 0.39101657 0.77964866]
   [0.16012329 0.22870962 0.7676354 ]
   [0.29902482 0.46543393 0.78578466]
   [0.31523076 0.20775472 0.5884085 ]
   [0.43712533 0.40460333 0.58299816]
   [0.42217934 0.14877686 0.6569218 ]
   [0.44656217 0.35862112 0.8418989 ]
   [0.4509836  0.27818206 0.69684243]
   [0.6594478  0.31161278 0.66359234]
   [0.6532317  0.29183242 0.5631411 ]
   [0.80249584 0.33340415 0.4849565 ]
   [0.7892081  0.3330079  0.37380397]]]]
[[[[0.01597054 0.2759514  0.04083863]
   [0.00562593 0.28657606 0.02525482]
   [0.00811316 0.26413304 0.0216468 ]
   [0.02016556 0.33125794 0.07537746]
   [0.02682813 0.28072453 0.06236115]
   [0.14417279 0.39101657 0.77964866]
   [0.16012329 0.22870962 0.7676354 ]
   [0.29902482 0.46543393 0.78578466]
   [0.31523076 0.20775472 0.5884085 ]
   [0.437

[[[[0.02092191 0.25135282 0.06381628]
   [0.01164142 0.26049206 0.04507548]
   [0.01326647 0.23609984 0.03802904]
   [0.02145971 0.27816656 0.11942521]
   [0.02805487 0.21917781 0.07879192]
   [0.13644879 0.35288712 0.8640599 ]
   [0.15975606 0.15755285 0.71258396]
   [0.29639778 0.4314669  0.8393252 ]
   [0.33777523 0.13329566 0.75503445]
   [0.44295943 0.42852372 0.64357984]
   [0.46783146 0.12613116 0.53348774]
   [0.44112915 0.36390948 0.86865056]
   [0.46651706 0.26437932 0.7930143 ]
   [0.66176564 0.41941422 0.4788628 ]
   [0.6544153  0.2811062  0.55880064]
   [0.61991596 0.5792897  0.45081842]
   [0.7806417  0.33098662 0.40638286]]]]
[[[[0.02092191 0.25135282 0.06381628]
   [0.01164142 0.26049206 0.04507548]
   [0.01326647 0.23609984 0.03802904]
   [0.02145971 0.27816656 0.11942521]
   [0.02805487 0.21917781 0.07879192]
   [0.13644879 0.35288712 0.8640599 ]
   [0.15975606 0.15755285 0.71258396]
   [0.29639778 0.4314669  0.8393252 ]
   [0.33777523 0.13329566 0.75503445]
   [0.442

[[[[0.06085856 0.3384614  0.02092454]
   [0.02425238 0.34920225 0.0229429 ]
   [0.02398955 0.3289004  0.0355224 ]
   [0.05749762 0.37788832 0.05293971]
   [0.05123422 0.31075615 0.06646326]
   [0.16962454 0.43397784 0.7072229 ]
   [0.16411787 0.24888712 0.71430117]
   [0.32277876 0.47196    0.75503767]
   [0.31785464 0.2007144  0.5854676 ]
   [0.46892554 0.48837122 0.6515062 ]
   [0.4415573  0.19458054 0.6169461 ]
   [0.45847464 0.41544613 0.8560339 ]
   [0.46002525 0.29481375 0.8130969 ]
   [0.6756019  0.4717129  0.5404725 ]
   [0.65808815 0.29687566 0.6783057 ]
   [0.823081   0.5157627  0.22482532]
   [0.79190844 0.33187166 0.51258326]]]]
[[[[0.02068637 0.3941272  0.04265973]
   [0.01294916 0.4049223  0.03380564]
   [0.0121837  0.37968886 0.02622876]
   [0.0363837  0.4197088  0.08210784]
   [0.02971285 0.35541424 0.05496779]
   [0.16942772 0.45490798 0.63912934]
   [0.14341897 0.29002547 0.77085775]
   [0.32800996 0.48121998 0.60365564]
   [0.29844433 0.22271252 0.6298299 ]
   [0.473

[[[[0.26691583 0.6462234  0.44342035]
   [0.25642765 0.6594543  0.36418337]
   [0.24675226 0.6555905  0.43929046]
   [0.25267518 0.6543574  0.4759496 ]
   [0.21741262 0.6399056  0.5470483 ]
   [0.3086105  0.61259645 0.47503713]
   [0.19616865 0.51817596 0.60077864]
   [0.41408485 0.53333724 0.3999625 ]
   [0.27936453 0.46121973 0.5005761 ]
   [0.47252616 0.49839136 0.3150679 ]
   [0.290493   0.5313898  0.14702475]
   [0.47360298 0.4719062  0.75897956]
   [0.43109298 0.3663174  0.67710257]
   [0.66447014 0.47699422 0.6372187 ]
   [0.65103936 0.31323946 0.62668157]
   [0.78929746 0.4578453  0.3548931 ]
   [0.80923283 0.2542053  0.7746941 ]]]]
[[[[0.26691583 0.6462234  0.44342035]
   [0.25642765 0.6594543  0.36418337]
   [0.24675226 0.6555905  0.43929046]
   [0.25267518 0.6543574  0.4759496 ]
   [0.21741262 0.6399056  0.5470483 ]
   [0.3086105  0.61259645 0.47503713]
   [0.19616865 0.51817596 0.60077864]
   [0.41408485 0.53333724 0.3999625 ]
   [0.27936453 0.46121973 0.5005761 ]
   [0.472

[[[[0.13694246 0.563164   0.31003493]
   [0.13015528 0.5687021  0.27774554]
   [0.12121766 0.55410206 0.14121988]
   [0.13494524 0.555351   0.2341679 ]
   [0.10601588 0.51711667 0.21504006]
   [0.22680393 0.5260672  0.6252897 ]
   [0.1493814  0.40416953 0.752106  ]
   [0.37137625 0.5015211  0.6266041 ]
   [0.25452632 0.27287412 0.7948369 ]
   [0.47588718 0.4495251  0.26737663]
   [0.39903986 0.25197065 0.57818687]
   [0.48359567 0.4215159  0.8893882 ]
   [0.46786124 0.30811852 0.8089006 ]
   [0.70967615 0.4984903  0.6655416 ]
   [0.7142202  0.28995073 0.6232558 ]
   [0.81345624 0.5343605  0.1182065 ]
   [0.8192235  0.28528327 0.26011696]]]]
[[[[0.13694246 0.563164   0.31003493]
   [0.13015528 0.5687021  0.27774554]
   [0.12121766 0.55410206 0.14121988]
   [0.13494524 0.555351   0.2341679 ]
   [0.10601588 0.51711667 0.21504006]
   [0.22680393 0.5260672  0.6252897 ]
   [0.1493814  0.40416953 0.752106  ]
   [0.37137625 0.5015211  0.6266041 ]
   [0.25452632 0.27287412 0.7948369 ]
   [0.475

[[[[0.09439882 0.5601571  0.08016828]
   [0.04883788 0.5780092  0.03034636]
   [0.02819455 0.5435039  0.03271028]
   [0.08316043 0.61571944 0.09311259]
   [0.05545863 0.5261556  0.07400167]
   [0.23631488 0.6592227  0.61096096]
   [0.14314978 0.41546756 0.7806839 ]
   [0.4267952  0.6583399  0.72419095]
   [0.3023467  0.3018342  0.7303977 ]
   [0.6024232  0.6649348  0.5316447 ]
   [0.4810397  0.227332   0.67172223]
   [0.49508995 0.5340554  0.7955942 ]
   [0.48515028 0.3724911  0.81225014]
   [0.76058865 0.5757301  0.5287321 ]
   [0.7973518  0.36195606 0.75130284]
   [0.7735616  0.8061422  0.22532651]
   [0.84229195 0.35133383 0.08147833]]]]
[[[[0.09439882 0.5601571  0.08016828]
   [0.04883788 0.5780092  0.03034636]
   [0.02819455 0.5435039  0.03271028]
   [0.08316043 0.61571944 0.09311259]
   [0.05545863 0.5261556  0.07400167]
   [0.23631488 0.6592227  0.61096096]
   [0.14314978 0.41546756 0.7806839 ]
   [0.4267952  0.6583399  0.72419095]
   [0.3023467  0.3018342  0.7303977 ]
   [0.602

[[[[0.34579143 0.5366483  0.6857597 ]
   [0.3197337  0.5602417  0.47379658]
   [0.3231032  0.5093971  0.791059  ]
   [0.33197176 0.5955666  0.6175933 ]
   [0.3402946  0.47548795 0.52453697]
   [0.42141467 0.6661053  0.7579962 ]
   [0.42358327 0.42771566 0.6320972 ]
   [0.5070769  0.75431675 0.66602904]
   [0.52230906 0.3634255  0.6067692 ]
   [0.6134517  0.7581159  0.21541664]
   [0.6510391  0.34549582 0.49034452]
   [0.6925005  0.6321703  0.7351622 ]
   [0.68586576 0.5012728  0.8193728 ]
   [0.774702   0.807099   0.37092316]
   [0.7787329  0.37044072 0.57827854]
   [0.695702   0.6678039  0.23629051]
   [0.7163028  0.5495694  0.2654602 ]]]]
[[[[0.34579143 0.5366483  0.6857597 ]
   [0.3197337  0.5602417  0.47379658]
   [0.3231032  0.5093971  0.791059  ]
   [0.33197176 0.5955666  0.6175933 ]
   [0.3402946  0.47548795 0.52453697]
   [0.42141467 0.6661053  0.7579962 ]
   [0.42358327 0.42771566 0.6320972 ]
   [0.5070769  0.75431675 0.66602904]
   [0.52230906 0.3634255  0.6067692 ]
   [0.613

[[[[0.3083223  0.50780433 0.74843276]
   [0.28815567 0.53135705 0.73587555]
   [0.29323846 0.48555273 0.6329726 ]
   [0.31445336 0.5776219  0.57234293]
   [0.32302755 0.46505016 0.7949245 ]
   [0.4018043  0.6379988  0.8491516 ]
   [0.4242565  0.42564905 0.9312271 ]
   [0.5086229  0.79084134 0.5824393 ]
   [0.5555799  0.35875362 0.6828136 ]
   [0.56062627 0.930118   0.32973975]
   [0.65617085 0.31661302 0.68348837]
   [0.67490953 0.630256   0.77809393]
   [0.6758444  0.49796447 0.8464974 ]
   [0.7717585  0.8013875  0.35926482]
   [0.7853553  0.36978933 0.54897964]
   [0.7017557  0.6634321  0.07592121]
   [0.7071358  0.5444016  0.15967119]]]]
[[[[0.31229195 0.50754786 0.6768154 ]
   [0.2906161  0.53105307 0.5852755 ]
   [0.29789332 0.48251694 0.69753826]
   [0.3122816  0.575513   0.5913778 ]
   [0.32522967 0.46095988 0.7168925 ]
   [0.40477085 0.6376252  0.84258544]
   [0.4280107  0.42702863 0.9226984 ]
   [0.5110632  0.8028709  0.58172697]
   [0.56949306 0.34911522 0.67473084]
   [0.570

[[[[0.29325354 0.5688896  0.69995284]
   [0.27388835 0.59266007 0.67610455]
   [0.275157   0.5441778  0.622931  ]
   [0.2993161  0.61868757 0.7798778 ]
   [0.30351835 0.5043239  0.7651361 ]
   [0.39853495 0.64715946 0.8795128 ]
   [0.40425807 0.44041085 0.88918614]
   [0.5322648  0.7372197  0.5799054 ]
   [0.5915598  0.42869246 0.7228954 ]
   [0.590237   0.8890501  0.46432048]
   [0.68818396 0.5438899  0.4482671 ]
   [0.6773758  0.5962211  0.6724927 ]
   [0.68066335 0.4457472  0.6485741 ]
   [0.7346287  0.8022716  0.45054537]
   [0.72847503 0.38507575 0.46298975]
   [0.8369981  0.7175888  0.22603348]
   [0.7141818  0.56147873 0.3165226 ]]]]
[[[[0.28773558 0.569835   0.7739439 ]
   [0.26665378 0.5928203  0.7648871 ]
   [0.26641646 0.54302645 0.6192238 ]
   [0.29255426 0.6141559  0.7667692 ]
   [0.2991375  0.49532768 0.6271702 ]
   [0.3959739  0.6506481  0.86519104]
   [0.41061652 0.4396003  0.89716625]
   [0.5360276  0.7560598  0.4940885 ]
   [0.58777964 0.46197242 0.48154035]
   [0.603

[[[[0.28090966 0.47930798 0.69622475]
   [0.2568867  0.507334   0.789582  ]
   [0.2560012  0.45037168 0.7915535 ]
   [0.28879946 0.5420817  0.5714026 ]
   [0.2921399  0.40768206 0.6988799 ]
   [0.40151662 0.58290076 0.70323443]
   [0.4183361  0.3454041  0.6927279 ]
   [0.55002403 0.73336905 0.729458  ]
   [0.63398373 0.40890154 0.54808867]
   [0.6102851  0.9591609  0.5795255 ]
   [0.75438917 0.5421512  0.4767827 ]
   [0.723618   0.56048554 0.72779334]
   [0.73716855 0.40137348 0.7020242 ]
   [0.7500083  0.79002726 0.46949282]
   [0.78464067 0.25025263 0.37637404]
   [0.8408859  0.71884704 0.21951461]
   [0.7833885  0.56382215 0.12275335]]]]
[[[[0.2798745  0.4728667  0.79654336]
   [0.25881287 0.50165915 0.706564  ]
   [0.2559273  0.44596037 0.84028083]
   [0.2963636  0.5399071  0.51779234]
   [0.290083   0.40651554 0.7215983 ]
   [0.40078825 0.5784107  0.8749317 ]
   [0.41608784 0.34667486 0.86462873]
   [0.54962236 0.7338113  0.72392213]
   [0.6146068  0.38861442 0.6136145 ]
   [0.612

[[[[0.2750036  0.38658184 0.7726252 ]
   [0.24931154 0.4157679  0.4606232 ]
   [0.25288692 0.35123715 0.5516015 ]
   [0.28978333 0.45081043 0.56682754]
   [0.29741913 0.30116218 0.83489645]
   [0.4194675  0.4956556  0.8342233 ]
   [0.42879373 0.24039325 0.75055695]
   [0.54937    0.7041583  0.6667614 ]
   [0.6815421  0.15503992 0.71342385]
   [0.59196186 0.89776254 0.27490494]
   [0.66474307 0.405022   0.66458666]
   [0.8224598  0.49402222 0.61744463]
   [0.8451208  0.32765758 0.64810026]
   [0.8646885  0.7076461  0.08228952]
   [0.83364236 0.46765038 0.02393451]
   [0.8512664  0.60712385 0.01178789]
   [0.71800363 0.4594531  0.12076822]]]]
[[[[0.27898955 0.37297547 0.5959144 ]
   [0.25154567 0.40336496 0.7051502 ]
   [0.25505027 0.33659384 0.7510141 ]
   [0.28915045 0.43882793 0.50508285]
   [0.29757968 0.288522   0.79704326]
   [0.42036745 0.4863695  0.8427417 ]
   [0.42891502 0.23496869 0.6932258 ]
   [0.5538668  0.70399064 0.6633694 ]
   [0.6808941  0.15829128 0.6025726 ]
   [0.596

[[[[0.2806825  0.36258543 0.8403749 ]
   [0.24815916 0.39664996 0.53619903]
   [0.25684938 0.32365602 0.77650815]
   [0.28738183 0.44853783 0.5872249 ]
   [0.30810043 0.28130132 0.7319284 ]
   [0.404257   0.5153507  0.8522446 ]
   [0.46454486 0.25013423 0.89784837]
   [0.5802195  0.69803286 0.6001931 ]
   [0.6985435  0.30821875 0.50592756]
   [0.60993785 0.92680734 0.43701085]
   [0.8070597  0.528267   0.17768726]
   [0.77998316 0.60650307 0.593452  ]
   [0.8193011  0.38573787 0.47234806]
   [0.77387166 0.8130883  0.29218006]
   [0.83247876 0.5570134  0.23709336]
   [0.842757   0.74160707 0.07611954]
   [0.8570236  0.7287411  0.14519754]]]]
[[[[0.2819338  0.3687342  0.55380106]
   [0.2520257  0.4029547  0.56491727]
   [0.25821728 0.3300766  0.65489286]
   [0.29261184 0.45970938 0.41306156]
   [0.31151646 0.286897   0.48125127]
   [0.41033822 0.5239024  0.89398617]
   [0.46648657 0.25360382 0.6024012 ]
   [0.5807454  0.6974322  0.5527417 ]
   [0.7033546  0.31634402 0.4275439 ]
   [0.608

[[[[0.29541412 0.51680714 0.70837283]
   [0.27064633 0.5481399  0.6270044 ]
   [0.2699066  0.4828155  0.7163718 ]
   [0.31706303 0.58478606 0.45404264]
   [0.3126529  0.43036717 0.8068408 ]
   [0.44237766 0.62944674 0.68332106]
   [0.43282175 0.36687046 0.8063967 ]
   [0.54971886 0.8441609  0.6359565 ]
   [0.69314027 0.3707136  0.3209831 ]
   [0.64601743 0.98276895 0.11457098]
   [0.8147241  0.51126456 0.1668137 ]
   [0.8054147  0.61950624 0.47857746]
   [0.82399774 0.4298178  0.5418692 ]
   [0.73607177 0.81434005 0.26618397]
   [0.5862802  0.32856664 0.13001773]
   [0.84092915 0.6632688  0.06228969]
   [0.84367645 0.63622653 0.07498294]]]]
[[[[0.29541412 0.51680714 0.70837283]
   [0.27064633 0.5481399  0.6270044 ]
   [0.2699066  0.4828155  0.7163718 ]
   [0.31706303 0.58478606 0.45404264]
   [0.3126529  0.43036717 0.8068408 ]
   [0.44237766 0.62944674 0.68332106]
   [0.43282175 0.36687046 0.8063967 ]
   [0.54971886 0.8441609  0.6359565 ]
   [0.69314027 0.3707136  0.3209831 ]
   [0.646

[[[[0.31103295 0.5664921  0.517479  ]
   [0.29114252 0.5958011  0.6967971 ]
   [0.2783968  0.53178596 0.87040395]
   [0.33121842 0.6130712  0.56170434]
   [0.31209314 0.46703863 0.6656024 ]
   [0.4491776  0.63838005 0.74353635]
   [0.42990476 0.38425577 0.6442286 ]
   [0.5585289  0.8271862  0.63244593]
   [0.6437568  0.35534257 0.5792235 ]
   [0.63869584 0.9845667  0.2727129 ]
   [0.83295727 0.5075945  0.32849622]
   [0.79395074 0.6233176  0.5804333 ]
   [0.8079771  0.4344102  0.6183821 ]
   [0.759092   0.81707656 0.22018626]
   [0.8247032  0.542926   0.17871413]
   [0.860667   0.65559196 0.11231223]
   [0.8617844  0.6021975  0.09465352]]]]
[[[[0.3086612  0.5645424  0.4651479 ]
   [0.28840205 0.5942478  0.7721389 ]
   [0.2765811  0.5294101  0.8550784 ]
   [0.33199728 0.61490154 0.5556664 ]
   [0.31268907 0.4661288  0.7038396 ]
   [0.4496042  0.6388507  0.7272619 ]
   [0.4279197  0.38049334 0.9266436 ]
   [0.5579339  0.8281202  0.6103948 ]
   [0.67510813 0.37651703 0.35371438]
   [0.638

[[[[0.32345605 0.61945254 0.71063256]
   [0.29373574 0.63215333 0.79326236]
   [0.28608608 0.57944053 0.75807214]
   [0.30641422 0.5909785  0.58661324]
   [0.30346763 0.48295042 0.7697451 ]
   [0.4409283  0.65297467 0.87991667]
   [0.43793473 0.37888205 0.82300067]
   [0.5628159  0.83139056 0.6934594 ]
   [0.69809616 0.39585656 0.32345092]
   [0.629625   0.9851314  0.27536836]
   [0.83488667 0.5410266  0.18520856]
   [0.8063578  0.62867534 0.532501  ]
   [0.83044827 0.45106623 0.46431264]
   [0.7601418  0.82409906 0.18074656]
   [0.82080334 0.5628951  0.12441424]
   [0.853573   0.7165017  0.03201771]
   [0.8584715  0.69941247 0.07183412]]]]
[[[[0.32676995 0.61534476 0.7377404 ]
   [0.29524568 0.63125217 0.7723788 ]
   [0.28840944 0.5773999  0.7342478 ]
   [0.30575782 0.597103   0.63507724]
   [0.30408198 0.48215994 0.7524124 ]
   [0.44549465 0.64927113 0.7111099 ]
   [0.43787515 0.37760407 0.83368707]
   [0.563614   0.83046293 0.6836236 ]
   [0.6989051  0.3909658  0.39216766]
   [0.639

In [5]:
#right eye
keypoints_with_scores[0][0][2]


array([0.84508383, 0.81688714, 0.5938909 ], dtype=float32)

In [6]:
#left elbow
keypoints_with_scores[0][0][7]
#Noramlized values so you need to multiply it by the dimension of the frame

array([0.84508383, 0.81688714, 0.5938909 ], dtype=float32)

### Draw Keypoints

In [7]:
def draw_keypoints(frame, keypoints, confidence_threshold):
    y, x, c = frame.shape
    shaped = np.squeeze(np.multiply(keypoints,[y, x, 1]))
    
    for kp in shaped:
        ky, kx, kp_conf = kp
        if kp_conf > confidence_threshold:
            cv2.circle(frame,(int(kx),int(ky)), 4, (0,255,0), -1)
    
    

### Draw Edges

In [9]:
# this is for connecting the different parts of the body to each other taken directly fromt a source
EDGES = {
    (0, 1): 'm',
    (0, 2): 'c',
    (1, 3): 'm',
    (2, 4): 'c',
    (0, 5): 'm',
    (0, 6): 'c',
    (5, 7): 'm',
    (7, 9): 'm',
    (6, 8): 'c',
    (8, 10): 'c',
    (5, 6): 'y',
    (5, 11): 'm',
    (6, 12): 'c',
    (11, 12): 'y',
    (11, 13): 'm',
    (13, 15): 'm',
    (12, 14): 'c',
    (14, 16): 'c'
}

In [15]:
def draw_connections(frame, keypoints, edges, confidence_threshold):
    y, x, c = frame.shape
    shaped = np.squeeze(np.multiply(keypoints,[y, x, 1]))
    
    for edge, color in edges.items():
        p1, p2 = edge
        y1, x1, c1 = shaped[p1]
        y2, x2, c2 = shaped[p2]
        if (c1 > confidence_threshold) & (c2 > confidence_threshold):
            cv2.line(frame, (int(x1), int(y1)), (int(x2), int(y2)), (255, 0, 0), 2 )